# simulation
strategy = "octree"
scenario = "ring"
integrator = "verlet"
duration = 50
timestep = 1e-2
output_interval = 1e-1
nozmom = false
num_bodies = 1024
seed = 42

# output 
output = "ring.csv"

# visualization
viz = true
viz_show_orbits = false
viz_speed_factor = 1.0
viz_trail_length = 1.0
viz_trail_segments = 10
viz_size_scale = 300.0
viz_size_min = 2.0
viz_size_max = 32.0
viz_orbit_width = 3.0